version: '3.8'

services:
  # Servicio para MailHog (Servidor SMTP)
  smtp:
    build:
      context: ./mailhog
    container_name: mailhog
    ports:
      - "1025:1025"   # Puerto SMTP de MailHog
      - "8025:8025"   # Interfaz web de MailHog
    networks:
      - mail_network

  # Servicio para MySQL
  db:
    build:
      context: ./mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: servidor
    ports:
      - "3308:3306"
    networks:
      - mail_network

  # Servicio para la aplicaci贸n PHP con Apache
  php-apache:
    build:
      context: ./app
    container_name: php-apache
    ports:
      - "8080:80"     # Puerto para acceder a la aplicaci贸n en localhost
    volumes:
      - ./app:/var/www/html   # Montar el c贸digo de la aplicaci贸n para desarrollo
    networks:
      - mail_network
    depends_on:
      - db
      - smtp

networks:
  mail_network:
    driver: bridge
